### ISSUE TITLE
Delivery Module

### ISSUE THREAD

**Issue by Eyu-dreamer** [MyTeamOrgo/Rest-Apk#1]
Add real-time order tracking

Description: Implement live tracking for delivery orders using GPS.
Priority: High
Assignee: Backend Developer (Alice)
Label: feature, backend, urgent
Fix delivery time calculation bug

Description: Address incorrect ETA calculations for deliveries during peak hours.
Priority: Medium
Assignee: Backend Developer (Alice)
Label: bug, backend
Design delivery dashboard UI

Description: Create a clean, user-friendly interface for delivery personnel to manage their tasks.
Priority: High
Assignee: Frontend Developer (Bob)
Label: design, frontend
Push order status notifications to customers

Description: Notify customers when their order status changes (e.g., order placed, prepared, out for delivery).
Priority: High
Assignee: Backend Developer (Alice)
Label: feature, backend

**Comment by Eyu-dreamer** [comment]
This is a front-end developer task delegation

**Comment by eyu-dreamer-2** [comment]
Okay, I would do my best.
